

export const rows = [
  {
    id: 1,
    name: "Amanj shkur",
    email: "Amanjshkur@gmail.com",
    age: 20,
    phone: "0751 522 4100",
    access: "Admin",
  },
  {
    id: 2,
    name: "Dana bestun",
    email: "Danabestun@gmail.com",
    age: 22,
    phone: "0751 356 5100",
    access: "Admin",
  },
  {
    id: 3,
    name: "Ahmed salar",
    email: "Ahmedsalar@gmail.com",
    age: 45,
    phone: "0750 112 4155",
    access: "Admin",
  },
  {
    id: 4,
    name: "Raman mheden",
    email: "Ramanmheden@gmail.com",
    age: 23,
    phone: "0750 442 5624",
    access: "Manager",
  },
  {
    id: 5,
    name: "Aso shkur",
    email: "Asoshkur@gmail.com",
    age: 21,
    phone: "0750 446 2136",
    access: "Manager",
  },
  {
    id: 6,
    name: "Yassin hussen",
    email: "yassinhussen@gmail.com",
    age: 20,
    phone: "0780 425 6635",
    access: "User",
  },
  {
    id: 7,
    name: "Sina Srud",
    email: "sinasrud@gmail.com",
    age: 24,
    phone: "0750 456 1236",
    access: "User",
  },
  {
    id: 8,
    name: "Aryas nzar",
    email: "aryasnzar@gmail.com",
    age: 26,
    phone: "0750 258 1496",
    access: "User",
  },
  {
    id: 9,
    name: "Masud saman",
    email: "masusaman@gmail.com",
    age: 25,
    phone: "0750 129 5748",
    access: "User",
  },
];
